#!/bin/bash

nomeMaquina=`hostname`

Instalar(){
	apt-get install -y ssmtp
	apt-get install -y mutt
}

ConfigSSMTP(){
	echo "root=notificacao@ricardokeso.com" > /etc/ssmtp/ssmtp.conf
	echo " " >> /etc/ssmtp/ssmtp.conf
	echo "mailhub=smtp.gmail.com:587" >> /etc/ssmtp/ssmtp.conf
	echo " " >> /etc/ssmtp/ssmtp.conf
	echo "AuthUser=notificacao@ricardokeso.com" >> /etc/ssmtp/ssmtp.conf
	echo "AuthPass=135875.k" >> /etc/ssmtp/ssmtp.conf
	echo " " >> /etc/ssmtp/ssmtp.conf
	echo "UseTLS=YES" >> /etc/ssmtp/ssmtp.conf
	echo "UseSTARTTLS=YES" >> /etc/ssmtp/ssmtp.conf
	echo " " >> /etc/ssmtp/ssmtp.conf
	echo "rewhiteDomain=ricardokeso.com" >> /etc/ssmtp/ssmtp.conf
	echo "hostname=$nomeMaquina" >> /etc/ssmtp/ssmtp.conf
	echo " " >> /etc/ssmtp/ssmtp.conf
	echo "FromLineOverride=YES" >> /etc/ssmtp/ssmtp.conf
	
	echo "root=notificacao@ricardokeso.com" >> /etc/ssmtp/revaliases
}

EmailHeader(){
	touch /etc/ssmtp/header.txt
	echo "From: \"NOTIFICACAO TEST\" <notificacao@ricardokeso.com>" > /etc/ssmtp/header.txt
	echo "To: ricardo.keso@gmail.com" >> /etc/ssmtp/header.txt
	echo "Subject: $nomeMaquina.RicardoKeso.com - Test Email" >> /etc/ssmtp/header.txt
	echo " " >> /etc/ssmtp/header.txt
	echo "Send By SSMTP + MUTT" >> /etc/ssmtp/header.txt
}

AnexoTeste(){
	touch /etc/ssmtp/anexo.txt
	echo " " > /etc/ssmtp/anexo.txt
	echo "Send By SSMTP + MUTT" >> /etc/ssmtp/anexo.txt
}

Instalar
ConfigSSMTP
EmailHeader
AnexoTeste

mutt ricardo.keso@gmail.com -H /etc/ssmtp/header.txt -a /etc/ssmtp/anexo.txt < /dev/null
